-- 코드를 작성해주세요
SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO ii
JOIN ITEM_TREE it
  ON ii.ITEM_ID = it.ITEM_ID
LEFT JOIN ITEM_TREE child
  ON child.PARENT_ITEM_ID = it.ITEM_ID
WHERE child.ITEM_ID IS NULL
ORDER BY ii.ITEM_ID DESC;