-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.NAME
FROM ANIMAL_INS i
JOIN ANIMAL_OUTS o
 ON i.ANIMAL_ID=o.ANIMAL_ID
WHERE o.ANIMAL_ID IS NOT NULL
ORDER BY TIMESTAMPDIFF(SECOND, i.DATETIME, o.DATETIME) DESC
LIMIT 2;