-- 코드를 작성해주세요
SELECT c.ITEM_ID, ci.ITEM_NAME, ci.RARITY
FROM ITEM_TREE c
JOIN ITEM_INFO p
  ON p.ITEM_ID = c.PARENT_ITEM_ID
JOIN ITEM_INFO ci
  ON ci.ITEM_ID = c.ITEM_ID
WHERE p.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;