-- 코드를 작성해주세요
SELECT 
    fi.ID,
    fn.FISH_NAME,
    fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fn 
    ON fi.FISH_TYPE = fn.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) m 
    ON fi.FISH_TYPE = m.FISH_TYPE 
   AND fi.LENGTH = m.MAX_LENGTH
ORDER BY fi.ID ASC;