-- 코드를 작성해주세요
WITH score_2022 AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT s.SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM score_2022 s
JOIN HR_EMPLOYEES e
  ON e.EMP_NO = s.EMP_NO
WHERE s.SCORE = (SELECT MAX(SCORE) FROM score_2022);