-- 코드를 입력하세요
SELECT gb.TITLE,gb.BOARD_ID,gr.REPLY_ID,gr.WRITER_ID,gr.CONTENTS,DATE_FORMAT(gr.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD gb
JOIN USED_GOODS_REPLY gr ON gb.BOARD_ID=gr.BOARD_ID
WHERE gb.CREATED_DATE>="2022-10-01" AND gb.CREATED_DATE<'2022-11-01'
ORDER BY gr.CREATED_DATE ASC,gb.TITLE ASC;
